SELECT * FROM HI;
CREATE OR REPLACE PROCEDURE TEINF0(
TENAME OUT TE.TE_NAME%TYPE,
CLCODE OUT TE.TE_CLCODE%TYPE,
GRCODE OUT TE.TE_GRCODE%TYPE,
SUNAME OUT SU.SU_NAME%TYPE,
TELEVEL OUT TE.TE_LEVEL%TYPE,
STCOUNT OUT NUMBER,
TECODE IN TE.TE_CODE%TYPE,
TEPWD IN TE.TE_PWD%TYPE
)
IS
COMPARE NUMBER :=1;
RESULT0 NUMBER;
BEGIN
SELECT COUNT(*) INTO RESULT0 FROM TE WHERE TE_CODE = TECODE;
IF RESULT0=COMPARE
THEN 
RESULT0:=0;
SELECT COUNT(*) INTO RESULT0 FROM TE WHERE TE_CODE = TECODE AND TE_PWD = TEPWD;
IF RESULT0=COMPARE
THEN
SELECT TE_NAME, TE_CLCODE, TE_GRCODE, COUNT(ST_CODE), SU_NAME, TE_LEVEL
INTO TENAME, CLCODE, GRCODE, STCOUNT, SUNAME, TELEVEL FROM TE INNER JOIN ST ON TE_CLCODE=ST_CLCODE AND TE_GRCODE = ST_GRCODE
        INNER JOIN SU ON TE_SUCODE=SU_CODE
WHERE TE_CODE=TECODE AND TE_PWD=TEPWD AND ST_STATE='C'
GROUP BY TE_NAME, TE_CLCODE, TE_GRCODE,SU_NAME,TE_LEVEL;
INSERT INTO HI VALUES(TECODE,SYSDATE,'1');
IF STUDENTS IS NULL THEN
            RAISE CANNOT_COUNT;
        END IF;
END IF;
END IF;

END TEINF0;

SET SERVEROUTPUT ON;

DECLARE 
TENAME NVARCHAR2(5);
CLCODE NVARCHAR2(10);
GRCODE NVARCHAR2(10);
SUNAME NVARCHAR2(10);
TELEVEL NVARCHAR2(10);
STCOUNT NVARCHAR2(10);
BEGIN
TEINF0(TENAME,CLCODE, GRCODE, SUNAME, TELEVEL, STCOUNT, '1005','0000');
DBMS_OUTPUT.PUT_LINE('TENAME : '||TENAME);
DBMS_OUTPUT.PUT_LINE('TENAME : '||CLCODE);
DBMS_OUTPUT.PUT_LINE('TENAME : '||GRCODE);
DBMS_OUTPUT.PUT_LINE('TENAME : '||SUNAME);
DBMS_OUTPUT.PUT_LINE('TENAME : '||TELEVEL);
DBMS_OUTPUT.PUT_LINE('TENAME : '||STCOUNT);
END;